version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: bucketlist_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wish
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bucketlist-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081
    networks:
      - bucketlist-network

volumes:
  postgres_data:

networks:
  bucketlist-network:
